<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>ClienteCentroComputo</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="..\CentroComputo.Core\CentroComputo.Core.csproj"/></ItemGroup></Project>
