using System.Runtime.InteropServices;using System.Text.RegularExpressions;using System.Windows;using System.Windows.Input;using CentroComputo.Core;
namespace CentroComputo.Client;
public partial class LockWindow:Window
{
    private readonly ClientConfig config;private readonly ServerClient client;private readonly CancellationTokenSource stop=new();private readonly System.Windows.Forms.NotifyIcon tray;private string? activeSession,activeStudent;private bool locked=true;
    public LockWindow(ClientConfig config,ServerClient client){InitializeComponent();this.config=config;this.client=client;Device.Text=$"{config.Room}  ·  {config.ComputerName}";client.ConnectionChanged+=online=>Dispatcher.Invoke(()=>OfflineBox.Visibility=online?Visibility.Collapsed:Visibility.Visible);client.CommandReceived+=c=>Dispatcher.Invoke(()=>HandleCommand(c));Closing+=(s,e)=>{if(!Keyboard.IsKeyDown(Key.LeftCtrl)||!Keyboard.IsKeyDown(Key.LeftShift)){e.Cancel=true;}};tray=new System.Windows.Forms.NotifyIcon{Icon=System.Drawing.SystemIcons.Shield,Text="CentroComputo · Sesión",Visible=true};var menu=new System.Windows.Forms.ContextMenuStrip();menu.Items.Add("Cerrar sesión",null,(_,_)=>Dispatcher.Invoke(async()=>await EndSessionAsync()));tray.ContextMenuStrip=menu;Closed+=(_,_)=>tray.Dispose();}
    public async Task StartAsync(){try{await client.InitializeAsync(config,stop.Token);}catch{OfflineBox.Visibility=Visibility.Visible;} _=HeartbeatLoop();_=InactivityLoop();_=ScreenshotLoop();}
    private async Task HeartbeatLoop(){while(!stop.IsCancellationRequested){try{await client.HeartbeatAsync(locked?ComputerStatus.LOCKED:ComputerStatus.IN_SESSION,activeStudent,stop.Token);await client.SyncAsync(stop.Token);}catch{}await Task.Delay(TimeSpan.FromSeconds(10),stop.Token);}}
    private void Student_PreviewTextInput(object sender,TextCompositionEventArgs e)=>e.Handled=!Regex.IsMatch(e.Text,"^[0-9-]+$");
    private async void Login_Click(object sender,RoutedEventArgs e){var student=Student.Text.Trim();var local=!client.Online;if(!Regex.IsMatch(student,"^[0-9-]+$")||student=="1"&&!local){Message.Text="Expediente inválido";return;}try{if(activeSession is not null){if(student!=activeStudent){Message.Text="Solo el expediente de la sesión activa puede reanudar";return;}}else{activeSession=await client.LoginAsync(student,local,stop.Token);activeStudent=student;}locked=false;Welcome.Text="Ingrese su expediente";Hide();Message.Text="Solo números y guion";}catch(Exception ex){Message.Text=ex.Message;}}
    private async Task InactivityLoop(){while(!stop.IsCancellationRequested){await Task.Delay(TimeSpan.FromSeconds(15),stop.Token);if(!locked&&NativeMethods.IdleTime>=TimeSpan.FromMinutes(5))await Dispatcher.InvokeAsync(LockForInactivityAsync);}}
    private async Task ScreenshotLoop(){while(!stop.IsCancellationRequested){await Task.Delay(TimeSpan.FromSeconds(3),stop.Token);if(!client.Online)continue;try{var bounds=System.Windows.Forms.Screen.PrimaryScreen!.Bounds;using var source=new System.Drawing.Bitmap(bounds.Width,bounds.Height);using(var graphics=System.Drawing.Graphics.FromImage(source))graphics.CopyFromScreen(bounds.Left,bounds.Top,0,0,bounds.Size);using var scaled=new System.Drawing.Bitmap(source,new System.Drawing.Size(480,270));using var stream=new MemoryStream();var codec=System.Drawing.Imaging.ImageCodecInfo.GetImageEncoders().First(x=>x.MimeType=="image/jpeg");using var parameters=new System.Drawing.Imaging.EncoderParameters(1);parameters.Param[0]=new System.Drawing.Imaging.EncoderParameter(System.Drawing.Imaging.Encoder.Quality,45L);scaled.Save(stream,codec,parameters);await client.UploadScreenshotAsync(stream.ToArray(),stop.Token);}catch{}}}
    public async Task LockForInactivityAsync(){locked=true;Welcome.Text="Sesión bloqueada por inactividad";Student.Clear();Show();Activate();await client.HeartbeatAsync(ComputerStatus.LOCKED,activeStudent,stop.Token);}
    public async Task EndSessionAsync(){if(activeSession is not null&&activeStudent is not null)await client.LogoutAsync(activeSession,activeStudent,stop.Token);activeSession=activeStudent=null;locked=true;Welcome.Text="Ingrese su expediente";Show();Activate();}
    private void HandleCommand(RemoteCommand command){switch(command.Type){case"LOCK":locked=true;Show();Activate();break;case"BLOCK_INPUT":NativeMethods.BlockInput(true);var timer=new System.Windows.Threading.DispatcherTimer{Interval=TimeSpan.FromSeconds(30)};timer.Tick+=(s,e)=>{NativeMethods.BlockInput(false);timer.Stop();};timer.Start();break;case"RESTORE_INPUT":NativeMethods.BlockInput(false);break;}}
    private void Help_Click(object sender,RoutedEventArgs e){var dialog=new AdminRecoveryWindow();if(dialog.ShowDialog()==true){NativeMethods.BlockInput(false);Hide();}}
    private void Window_KeyDown(object sender,KeyEventArgs e){if(e.Key==Key.F12&&Keyboard.Modifiers.HasFlag(ModifierKeys.Control)&&Keyboard.Modifiers.HasFlag(ModifierKeys.Shift)){NativeMethods.BlockInput(false);new AdminRecoveryWindow().ShowDialog();}}
    private static class NativeMethods{[StructLayout(LayoutKind.Sequential)]private struct LASTINPUTINFO{public uint cbSize;public uint dwTime;}[DllImport("user32.dll",SetLastError=true)]internal static extern bool BlockInput(bool block);[DllImport("user32.dll")]private static extern bool GetLastInputInfo(ref LASTINPUTINFO info);internal static TimeSpan IdleTime{get{var i=new LASTINPUTINFO{cbSize=(uint)Marshal.SizeOf<LASTINPUTINFO>()};return GetLastInputInfo(ref i)?TimeSpan.FromMilliseconds(unchecked((uint)Environment.TickCount)-i.dwTime):TimeSpan.Zero;}}}
}
