const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={token:localStorage.getItem('nexo_token'),computers:[],rooms:[],sessions:[],selected:new Set(),room:'all'};
const labels={IN_SESSION:'En sesión',LOCKED:'Bloqueada',OFFLINE:'Offline',IDLE:'Inactiva',ERROR:'Error',UPDATING:'Actualizando',UPDATE_FAILED:'Actualización fallida'};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>d?new Intl.DateTimeFormat('es-MX',{dateStyle:'short',timeStyle:'short'}).format(new Date(d)):'—';
const ago=d=>{if(!d)return'Nunca';const s=Math.floor((Date.now()-new Date(d))/1000);return s<60?`hace ${s}s`:s<3600?`hace ${Math.floor(s/60)}m`:fmt(d)};
const duration=s=>s==null?'En curso':s<3600?`${Math.floor(s/60)} min`:`${Math.floor(s/3600)} h ${Math.floor(s%3600/60)} min`;
const status=s=>`<span class="status status-${s}">${labels[s]||s}</span>`;
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${state.token}`,...opt.headers}});if(r.status===401){logout();throw Error('Sesión expirada')}const data=await r.json();if(!r.ok)throw Error(data.error||'Error de servidor');return data}
function toast(text){const el=document.createElement('div');el.className='toast';el.textContent=text;$('#toasts').append(el);setTimeout(()=>el.remove(),3200)}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify(data),headers:{Authorization:''}});state.token=result.token;localStorage.setItem('nexo_token',result.token);$('#admin-name').textContent=result.username;$('#admin-role').textContent=result.role;showApp()}catch(err){$('#login-error').textContent=err.message}});
function logout(){state.token=null;localStorage.removeItem('nexo_token');$('#app').classList.add('hidden');$('#login').classList.remove('hidden')};$('#logout').onclick=logout;
async function showApp(){try{await api('/api/me');$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await load()}catch{logout()}}
async function load(){const [dashboard,rooms,computers,sessions]=await Promise.all([api('/api/dashboard'),api('/api/rooms'),api('/api/computers'),api('/api/sessions')]);Object.assign(state,{dashboard,rooms,computers,sessions});renderAll()}
function renderAll(){renderStats();renderRooms();renderComputers();renderSessions();renderAudit().catch(()=>{})}
function renderStats(){const d=state.dashboard;const stats=[['Computadoras',d.total,'▦'],['Online',d.online,'●'],['En sesión',d.inSession,'↗'],['Bloqueadas',d.locked,'◇'],['Usuarios activos',d.activeUsers,'♙']];$('#stats').innerHTML=stats.map(x=>`<div class="stat"><div><span>${x[0]}</span><strong>${x[1]}</strong></div><i>${x[2]}</i></div>`).join('');const bad=state.computers.filter(c=>['OFFLINE','ERROR','UPDATE_FAILED'].includes(c.status));$('#attention-count').textContent=bad.length;$('#attention-list').innerHTML=bad.slice(0,5).map(c=>`<div class="list-row"><div class="row-icon">${c.name.slice(-2)}</div><div><b>${esc(c.name)}</b><small>${esc(c.room_name)} · ${esc(c.ip_address||'Sin IP')}</small></div>${status(c.status)}</div>`).join('')||'<p class="muted">Sin incidencias activas.</p>';$('#recent-sessions').innerHTML=state.sessions.slice(0,5).map(s=>`<div class="list-row"><div class="row-icon">${esc(s.student_number).slice(-2)}</div><div><b>${esc(s.student_number)}</b><small>${esc(s.computer_name)} · ${esc(s.room_name)}</small></div><small>${fmt(s.login_time)}</small></div>`).join('')||'<p class="muted">Todavía no hay sesiones.</p>'}
function roomData(){return state.rooms.map(r=>{const pcs=state.computers.filter(c=>c.room_id===r.id);return{...r,pcs,online:pcs.filter(c=>c.status!=='OFFLINE').length,active:pcs.filter(c=>c.status==='IN_SESSION').length}})}
function renderRooms(){$('#room-summary').innerHTML=roomData().slice(0,3).map(r=>`<article class="room-card" data-room="${r.id}"><div class="room-card-top"><div><h3>${esc(r.name)}</h3><p>${esc(r.description||'Sala institucional')}</p></div><span class="pill">${r.pcs.length} equipos</span></div><div class="room-meter"><i style="width:${r.pcs.length?r.online/r.pcs.length*100:0}%"></i></div><div class="room-counts"><span><b>${r.online}</b> online</span><span><b>${r.active}</b> en sesión</span><span><b>${r.pcs.length-r.online}</b> offline</span></div></article>`).join('');$('#room-tabs').innerHTML=`<button data-room="all" class="${state.room==='all'?'active':''}">Todas</button>`+roomData().map(r=>`<button data-room="${r.id}" class="${state.room===r.id?'active':''}">${esc(r.name)} · ${r.pcs.length}</button>`).join('');$$('[data-room]').forEach(b=>b.onclick=()=>{state.room=b.dataset.room;showView('rooms');renderRooms();renderComputers()})}
function filteredComputers(){const q=$('#global-search').value.toLowerCase();return state.computers.filter(c=>(state.room==='all'||c.room_id===state.room)&&(!q||JSON.stringify(c).toLowerCase().includes(q)))}
function renderComputers(){const pcs=filteredComputers();$('#computer-grid').innerHTML=pcs.map(c=>`<article class="computer-card ${state.selected.has(c.id)?'selected':''}" data-id="${c.id}"><input type="checkbox" ${state.selected.has(c.id)?'checked':''}><div class="thumb ${c.screenshot_url?'has-image':''}" ${c.screenshot_url?`style="background-image:url('${esc(c.screenshot_url)}')"`:''} title="Doble clic para ampliar"></div><div class="computer-body"><div class="computer-title"><h3>${esc(c.name)}</h3>${status(c.status)}</div><div class="computer-meta"><span>IP<b>${esc(c.ip_address||'—')}</b></span><span>Expediente<b>${esc(c.current_student||'—')}</b></span><span>Sala<b>${esc(c.room_name)}</b></span><span>Última conexión<b>${ago(c.last_seen)}</b></span></div></div></article>`).join('')||'<div class="empty-card"><h2>Sin equipos</h2><p>No hay coincidencias para este filtro.</p></div>';$$('.computer-card input').forEach(x=>x.onchange=()=>{const id=x.closest('article').dataset.id;x.checked?state.selected.add(id):state.selected.delete(id);renderComputers()});$$('.thumb').forEach(x=>x.ondblclick=()=>openScreen(x.closest('article').dataset.id));$('#selected-count').textContent=`${state.selected.size} seleccionados`;$('#computers-table').innerHTML=state.computers.map(c=>`<tr><td><input type="checkbox" data-id="${c.id}"></td><td><strong>${esc(c.name)}</strong></td><td>${esc(c.room_name)}</td><td>${esc(c.ip_address||'—')}</td><td>${status(c.status)}</td><td>${esc(c.current_student||'—')}</td><td>${esc(c.client_version)}</td><td>${ago(c.last_seen)}</td></tr>`).join('')}
function renderSessions(){const q=$('#global-search').value.toLowerCase();$('#sessions-table').innerHTML=state.sessions.filter(s=>!q||JSON.stringify(s).toLowerCase().includes(q)).map(s=>`<tr><td><strong>${esc(s.student_number)}</strong></td><td>${esc(s.room_name)}</td><td>${esc(s.computer_name)}</td><td>${fmt(s.login_time)}</td><td>${fmt(s.logout_time)}</td><td>${duration(s.duration_seconds)}</td><td>${s.offline_mode?'<span class="pill">Sincronizada</span>':'Servidor'}</td></tr>`).join('')||'<tr><td colspan="7">No hay sesiones registradas.</td></tr>'}
async function renderAudit(){const rows=await api('/api/audit');$('#audit-table').innerHTML=rows.map(a=>`<tr><td>${fmt(a.timestamp)}</td><td>${esc(a.admin_username)}</td><td><strong>${esc(a.action)}</strong></td><td>${esc(a.computer_id||'—')}</td><td>${esc(a.result)}</td></tr>`).join('')||'<tr><td colspan="5">Sin acciones administrativas.</td></tr>'}
function showView(view){$$('.view').forEach(v=>v.classList.add('hidden'));$(`#view-${view}`).classList.remove('hidden');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#page-title').textContent={dashboard:'Dashboard',rooms:'Salas',computers:'Equipos',sessions:'Sesiones',updates:'Actualizaciones',settings:'Configuración',audit:'Auditoría'}[view];$('.sidebar').classList.remove('open')}
$$('#nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('#mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');
$('#global-search').oninput=()=>{renderComputers();renderSessions()};
$$('[data-command]').forEach(b=>b.onclick=async()=>{if(!state.selected.size)return toast('Selecciona al menos un equipo');try{await api('/api/commands',{method:'POST',body:JSON.stringify({computerIds:[...state.selected],type:b.dataset.command,payload:{}})});toast(`Comando ${b.dataset.command} enviado`);state.selected.clear();renderComputers()}catch(e){toast(e.message)}});
function openScreen(id){const c=state.computers.find(x=>x.id===id);$('.screen-large').innerHTML=c.screenshot_url?`<img src="${esc(c.screenshot_url)}" alt="Pantalla actual de ${esc(c.name)}">`:'<div class="screen-placeholder"><span>NEXO</span><p>Miniatura no disponible</p></div>';$('#dialog-name').textContent=c.name;$('#dialog-meta').textContent=`${c.room_name} · ${c.ip_address||'Sin IP'} · ${c.current_student||'Sin expediente'}`;$('#dialog-status').innerHTML=status(c.status);$('#screen-dialog').showModal()}$('.dialog-close').onclick=()=>$('#screen-dialog').close();
setInterval(()=>{const d=new Date();$('#clock').textContent=d.toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'});$('#today').textContent=d.toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long'})},1000);setInterval(()=>state.token&&load().catch(()=>{}),10000);
if(state.token)showApp();
