using System.Net.Http.Json;
using System.Net.WebSockets;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
namespace CentroComputo.Core;
public sealed partial class ServerClient(HttpClient http,ConfigStore configStore)
{
    private ClientConfig? config;
    public bool Online {get;private set;}
    public event Action<bool>? ConnectionChanged;
    public event Action<RemoteCommand>? CommandReceived;
    [GeneratedRegex("^[0-9-]+$")] private static partial Regex StudentPattern();
    public async Task InitializeAsync(ClientConfig value,CancellationToken ct){config=value;http.BaseAddress=new Uri(value.Server.TrimEnd('/')+"/");if(!value.IsRegistered)config=await RegisterAsync(value,ct);await ConnectCommandsAsync(ct);}
    private async Task<ClientConfig> RegisterAsync(ClientConfig value,CancellationToken ct){using var request=new HttpRequestMessage(HttpMethod.Post,"api/clients/register");request.Headers.Add("X-Registration-Secret",value.RegistrationSecret??"");request.Content=JsonContent.Create(new{uuid=Guid.NewGuid(),name=value.ComputerName,room=value.Room,ip=GetLocalIp(),version="1.0.0"});using var response=await http.SendAsync(request,ct);response.EnsureSuccessStatusCode();var result=await response.Content.ReadFromJsonAsync<RegistrationResponse>(ct)??throw new InvalidDataException("Respuesta de registro inválida");var saved=value with{ComputerId=result.ComputerId,ClientToken=result.ClientToken};await configStore.SaveAsync(saved);return saved;}
    private HttpRequestMessage Request(HttpMethod method,string uri,object? body=null){var r=new HttpRequestMessage(method,uri);r.Headers.Add("X-Client-Token",config!.ClientToken);if(body is not null)r.Content=JsonContent.Create(body);return r;}
    public async Task HeartbeatAsync(ComputerStatus status,string? student,CancellationToken ct){try{using var req=Request(HttpMethod.Post,$"api/clients/{config!.ComputerId}/heartbeat",new{status=status.ToString(),student,ip=GetLocalIp(),version="1.0.0"});using var res=await http.SendAsync(req,ct);res.EnsureSuccessStatusCode();SetOnline(true);}catch when(!ct.IsCancellationRequested){SetOnline(false);throw;}}
    public async Task<string> LoginAsync(string student,bool localMode,CancellationToken ct){if(!StudentPattern().IsMatch(student)||student=="1"&&!localMode)throw new ArgumentException("Expediente inválido");if(localMode){var e=new OfflineEvent(Guid.NewGuid(),"LOGIN",student,DateTimeOffset.UtcNow);await configStore.EnqueueAsync(e);return e.Id.ToString();}using var req=Request(HttpMethod.Post,$"api/clients/{config!.ComputerId}/sessions",new{studentNumber=student,offlineMode=false,loginTime=DateTimeOffset.UtcNow});using var res=await http.SendAsync(req,ct);res.EnsureSuccessStatusCode();return (await res.Content.ReadFromJsonAsync<SessionResponse>(ct))!.Id;}
    public async Task LogoutAsync(string sessionId,string student,CancellationToken ct){if(!Online){await configStore.EnqueueAsync(new(Guid.NewGuid(),"LOGOUT",student,DateTimeOffset.UtcNow,sessionId));return;}using var req=Request(HttpMethod.Post,$"api/clients/{config!.ComputerId}/sessions/{sessionId}/logout",new{logoutTime=DateTimeOffset.UtcNow});using var res=await http.SendAsync(req,ct);res.EnsureSuccessStatusCode();}
    public async Task SyncAsync(CancellationToken ct){var items=await configStore.ReadQueueAsync();if(items.Count==0)return;using var req=Request(HttpMethod.Post,$"api/clients/{config!.ComputerId}/sync",new{events=items.Select(e=>new{id=e.Id,type=e.Type,studentNumber=e.StudentNumber,timestamp=e.Timestamp,sessionId=e.SessionId})});using var res=await http.SendAsync(req,ct);res.EnsureSuccessStatusCode();var result=await res.Content.ReadFromJsonAsync<SyncResponse>(ct);await configStore.RemoveAcceptedAsync(result?.Accepted??[]);}
    public async Task UploadScreenshotAsync(byte[] jpeg,CancellationToken ct){if(!Online||jpeg.Length>180000)return;using var req=Request(HttpMethod.Post,$"api/clients/{config!.ComputerId}/screenshot",new{jpegBase64=Convert.ToBase64String(jpeg)});using var res=await http.SendAsync(req,ct);res.EnsureSuccessStatusCode();}
    private async Task ConnectCommandsAsync(CancellationToken ct){_ = Task.Run(async()=>{while(!ct.IsCancellationRequested){try{using var ws=new ClientWebSocket();var baseUri=new Uri(config!.Server);var scheme=baseUri.Scheme=="https"?"wss":"ws";var uri=new Uri($"{scheme}://{baseUri.Authority}/client-hub?computerId={config.ComputerId}&token={Uri.EscapeDataString(config.ClientToken!)}");await ws.ConnectAsync(uri,ct);var buffer=new byte[64*1024];while(ws.State==WebSocketState.Open&&!ct.IsCancellationRequested){var result=await ws.ReceiveAsync(buffer,ct);if(result.MessageType==WebSocketMessageType.Close)break;var json=Encoding.UTF8.GetString(buffer,0,result.Count);using var doc=JsonDocument.Parse(json);if(doc.RootElement.TryGetProperty("kind",out var kind)&&kind.GetString()=="command"){var command=doc.RootElement.GetProperty("command").Deserialize<RemoteCommand>(new JsonSerializerOptions(JsonSerializerDefaults.Web));if(command is not null)CommandReceived?.Invoke(command);}}}catch when(!ct.IsCancellationRequested){SetOnline(false);await Task.Delay(TimeSpan.FromSeconds(5),ct);}}},ct);}
    private void SetOnline(bool value){if(Online==value)return;Online=value;ConnectionChanged?.Invoke(value);}
    private static string GetLocalIp()=>System.Net.Dns.GetHostAddresses(System.Net.Dns.GetHostName()).FirstOrDefault(x=>x.AddressFamily==System.Net.Sockets.AddressFamily.InterNetwork)?.ToString()??"127.0.0.1";
    private sealed record RegistrationResponse(string ComputerId,string ClientToken,ClientSettings Settings);private sealed record SessionResponse(string Id);private sealed record SyncResponse(Guid[] Accepted);
}
